### ISSUE TITLE
Step 8 problem

### ISSUE THREAD

**Issue by RagnarokHero** [PierreCapo/jsrms#1]
Hello,

So I watched your video and followed the steps. Unfortunately, when I went to step 8 I got an error. I've tried restarting Visual Studio Code and even uninstalled everything from steps 1-4 and reinstalled it. Any idea what the issue maybe? 

![image](https://user-images.githubusercontent.com/65092242/81484928-9e8a7a80-9217-11ea-8c51-46e3ff1a4121.png)

**Comment by PierreCapo** [comment]
Hello @RagnarokHero !
Thanks for opening this issue, it's helping me improving the project.

This error is reporting you that it is not able to find the default path on your machine to save the map. My assumption is that you don't have TAD installed?

Anyway, I've just added in the README the explanation on how to write the path that suits your need: [specifying-a-custom-path-for-the-generated-map](https://github.com/PierreCapo/jsrms#specifying-a-custom-path-for-the-generated-map)

So you would need to have in your `jsrms.config.json` file like that if you want to have your map available for Vanilla for instance:

```JSON
{
    "sourceFile": "./compiler/map.js",
    "outputFolderPath": "C:\\Users\\chaot\\Documents\\My Games\\Age of Empires 3\\RM",
    "mapName": "___test",
    "mapDisplayName": "___test",
    "authorName": ""
}
```

Please keep me updated and tell me if that solves your problem.
Have a good day!

**Comment by RagnarokHero** [comment]
Hey @PierreCapo!

I do have TAD installed but your custom folder path solution worked. Thank you for your help and thanks for making this. I've already coded 7 RMS maps and can relate to how frustrating coding syntax errors can be. I'll be making my maps with this from this point forward. I heard you were on the ESOC Discord as well but couldn't find you. My Discord is Ragnarok_Hero #5562 if you would like to add me. Have a great day!
